# Generated by Django 4.2.5 on 2023-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico de contacto",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                ("contrasena", models.CharField(max_length=100)),
                (
                    "nick_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de usuario"
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cédula"
                    ),
                ),
                ("telefono", models.CharField(max_length=100, verbose_name="Teléfono")),
                (
                    "is_octavia",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Es cliente octavia"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Direccion"
                    ),
                ),
                ("locacion", models.CharField(max_length=100, verbose_name="Locación")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "created",
                    models.DateTimeField(editable=False, verbose_name="Fecha creación"),
                ),
                (
                    "fecha_activacion",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Fecha de activación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ("orden",),
            },
        ),
    ]
