# Generated by Django 4.2.5 on 2023-09-19 23:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps", "0001_initial"),
        ("clientes", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "referencia_pasarela",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Referencia de la Pasarela",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(editable=False, verbose_name="Fecha compra"),
                ),
                ("total", models.PositiveIntegerField(default=0, verbose_name="Total")),
                (
                    "transaccion_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Transaccion de la Pasarela",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Metodo de Pago",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("proceso", "Proceso"),
                            ("aprobado", "Aprobado"),
                            ("pendiente_efectivo", "Pendiente Pago Efectivo"),
                            ("rechazado", "Rechazado"),
                            ("espera_respuesta_pasarela", "Respuesta de Pasarela"),
                            ("error_pasarela", "Error en la Pasarela"),
                        ],
                        default="proceso",
                        max_length=45,
                        verbose_name="Estado",
                    ),
                ),
                ("razon_rechazado", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas_set",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "tipo_pasarela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pasarela_set",
                        to="apps.pasarelas",
                        verbose_name="Pasarela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.CreateModel(
            name="VentaProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "by_venta_caja",
                    models.BooleanField(default=False, verbose_name="Cantidad de Caja"),
                ),
                (
                    "by_mayor",
                    models.BooleanField(default=False, verbose_name="Cantidad x Mayor"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
                ),
                (
                    "precio",
                    models.PositiveIntegerField(default=0, verbose_name="Precio"),
                ),
                (
                    "especificaciones",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Especificaciones del producto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_venta",
                        to="inventario.producto",
                        verbose_name="Productos de la Venta",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venta_producto",
                        to="ventas.venta",
                        verbose_name="Venta del Producto",
                    ),
                ),
            ],
        ),
    ]
