# Generated by Django 4.1.5 on 2023-09-18 18:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=200)),
                ("imagen", models.ImageField(upload_to="teacompano-img/")),
            ],
        ),
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pagename",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la página"
                    ),
                ),
                (
                    "pagemetatitle",
                    models.CharField(
                        max_length=200, verbose_name="Metatítulo(title) de la página"
                    ),
                ),
                (
                    "pagetitle",
                    models.CharField(
                        max_length=200, verbose_name="Título(h1) de la página"
                    ),
                ),
                (
                    "pageslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan(h2) de la página"
                    ),
                ),
                (
                    "pagemetadesc",
                    ckeditor.fields.RichTextField(
                        verbose_name="Meta descripción de la página"
                    ),
                ),
                (
                    "pagekeywords",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave de la página"
                    ),
                ),
                (
                    "pagebanner",
                    models.ImageField(
                        default="/servicios/static/img/default.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen Banner de la página",
                    ),
                ),
                (
                    "pagebannermov",
                    models.ImageField(
                        default="/servicios/static/img/default-mov.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen Banner de la página en Móvil",
                    ),
                ),
                (
                    "pageogdesc",
                    models.CharField(
                        default="Descripción del sitio web",
                        max_length=400,
                        verbose_name="Descripción OG de la página",
                    ),
                ),
                (
                    "pageogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG de la página"
                    ),
                ),
                (
                    "pageogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato de la página"
                    ),
                ),
                (
                    "pageogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura de la página"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promoname",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la promoción"
                    ),
                ),
                (
                    "widepromo",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen wide promo",
                    ),
                ),
                (
                    "movilpromo",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen movil promo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "videoname",
                    models.CharField(max_length=200, verbose_name="Nombre del video"),
                ),
                (
                    "videourl",
                    models.CharField(max_length=200, verbose_name="URL del video"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productmetadesc",
                    models.CharField(
                        max_length=200, verbose_name="Meta descripción del Producto"
                    ),
                ),
                (
                    "productkeywords",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave del Producto"
                    ),
                ),
                (
                    "productbanner",
                    models.ImageField(
                        default="/productos/static/img/default.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen Banner del Producto",
                    ),
                ),
                (
                    "productbannermov",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen Banner del Producto en Móvil",
                    ),
                ),
                (
                    "productogdesc",
                    models.CharField(
                        max_length=200, verbose_name="Descripción OG del Producto"
                    ),
                ),
                (
                    "productogtitle",
                    models.CharField(
                        max_length=200, verbose_name="Metatítulo OG del Producto"
                    ),
                ),
                (
                    "productogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG del Producto"
                    ),
                ),
                (
                    "productogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato del Producto"
                    ),
                ),
                (
                    "productogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura del Producto"
                    ),
                ),
                (
                    "productname",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "productslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan del Producto"
                    ),
                ),
                (
                    "productoldprice",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Precio normal"
                    ),
                ),
                (
                    "productdiscount",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Valor de descuento",
                    ),
                ),
                (
                    "producturl",
                    models.CharField(
                        max_length=200, verbose_name="Url producto detalle"
                    ),
                ),
                ("productdescription", ckeditor.fields.RichTextField()),
                (
                    "productimg",
                    models.ImageField(
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen principal del Producto",
                    ),
                ),
                (
                    "gallerya",
                    models.ImageField(
                        blank=True,
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen secundaria del Producto",
                    ),
                ),
                (
                    "galleryb",
                    models.ImageField(
                        blank=True,
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen adicional del Producto",
                    ),
                ),
                (
                    "galleryc",
                    models.ImageField(
                        blank=True,
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen final del Producto",
                    ),
                ),
                (
                    "productprice",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Precio de venta",
                    ),
                ),
                ("productupdated", models.DateTimeField(auto_now=True)),
                (
                    "asesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apps.asesor",
                    ),
                ),
            ],
        ),
    ]
