# Generated by Django 4.1.5 on 2023-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagina",
            name="videourl",
            field=models.CharField(
                default="apps/static/img/default.jpg",
                max_length=200,
                verbose_name="Video de la página",
            ),
        ),
        migrations.AlterField(
            model_name="pagina",
            name="pagebanner",
            field=models.ImageField(
                default="apps/static/img/default.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página",
            ),
        ),
        migrations.AlterField(
            model_name="pagina",
            name="pagebannermov",
            field=models.ImageField(
                default="apps/static/img/default-c.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página en Móvil",
            ),
        ),
    ]
