# Generated by Django 4.1.5 on 2023-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_pagina_videourl_alter_pagina_pagebanner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagina",
            name="videourl",
            field=models.CharField(
                default="GduZ3mELr_E?si=xSvEBdzOXiQJN4gs",
                max_length=200,
                verbose_name="Video de la página",
            ),
        ),
    ]
