# Generated by Django 4.1.5 on 2023-09-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_pagina_videourl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gentitle", models.CharField(blank=True, max_length=400)),
                (
                    "genimg",
                    models.ImageField(
                        blank=True,
                        default="apps/static/img/default-c.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen para el generic",
                    ),
                ),
                ("gendesc", models.CharField(blank=True, max_length=400)),
                ("gencreated", models.DateTimeField(auto_now=True)),
                (
                    "genasesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apps.asesor",
                    ),
                ),
            ],
        ),
    ]
