# Generated by Django 4.1.5 on 2023-09-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_generic_gendesc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="destacado",
            field=models.BooleanField(default=False, verbose_name="Producto destacado"),
        ),
    ]
