# Generated by Django 4.1.5 on 2023-09-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_product_destacado"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productref",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Referencia del Producto"
            ),
        ),
    ]
