# Generated by Django 4.2.5 on 2023-09-19 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                ("url", models.SlugField(max_length=100, verbose_name="Url")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="uploads/inventario/imagenes/",
                        verbose_name="Foto categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría Producto",
                "verbose_name_plural": "Categorías Productos",
                "ordering": ("orden", "id"),
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=75, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "tipo_marca",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Original Octavia Lingerie"),
                            (1, "Marcas Autorizadas"),
                        ],
                        default=0,
                        verbose_name="Tipo de Marca",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="uploads/octavia/marcas/",
                        verbose_name="Logo Marca",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ("orden",),
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=39, unique=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Url",
                    ),
                ),
                ("nombre", models.CharField(max_length=75, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "codigo_video",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Código video YouTube",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="uploads/inventario/imagenes/",
                        verbose_name="Foto",
                    ),
                ),
                ("costo", models.FloatField(default=0.0, verbose_name="Costo")),
                (
                    "costo_octavia",
                    models.FloatField(default=0.0, verbose_name="Costo octavia"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "destacado",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Destacado"
                    ),
                ),
                (
                    "calificacion",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "1 estrella"),
                            (1, "2 estrella"),
                            (2, "3 estrella"),
                            (3, "4 estrella"),
                            (4, "5 estrella"),
                        ],
                        null=True,
                        verbose_name="Calificacion",
                    ),
                ),
                (
                    "cantidad_cajas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad x Cajas"
                    ),
                ),
                (
                    "cantidad_cajas_prefer",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad x Cajas octavia"
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(verbose_name="Cantidad en almacén"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "descripcion_prefer",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Descripcion del producto prefer",
                    ),
                ),
                (
                    "descripcion_no_prefer",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Descripcion del producto no prefer",
                    ),
                ),
                (
                    "costo_adicional",
                    models.FloatField(default=0.0, verbose_name="Costo Adicional"),
                ),
                (
                    "descripcion_adicional",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Descripcion Adicional del producto",
                    ),
                ),
                (
                    "by_producto_prefer",
                    models.BooleanField(default=False, verbose_name="Producto Prefer"),
                ),
                (
                    "by_producto_prefer_general",
                    models.BooleanField(
                        default=False, verbose_name="Producto Prefer y Generales"
                    ),
                ),
                (
                    "costo_prefer",
                    models.FloatField(default=0.0, verbose_name="Costo Prefer Caja"),
                ),
                (
                    "costo_caja_prefer",
                    models.FloatField(default=0.0, verbose_name="Costo Prefer Mayor"),
                ),
                (
                    "by_inactive_price_aditional",
                    models.BooleanField(
                        default=False, verbose_name="Inactivar precio adicional"
                    ),
                ),
                (
                    "by_inactive_price_octavia",
                    models.BooleanField(
                        default=False, verbose_name="Inactivar precio octavia"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_set",
                        to="inventario.categoriaproducto",
                        verbose_name="Categoría Producto",
                    ),
                ),
                (
                    "marca_producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marca_producto",
                        to="inventario.marca",
                        verbose_name="Marca Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ("orden",),
            },
        ),
        migrations.CreateModel(
            name="GaleriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to="uploads/inventario/imagenes/",
                        verbose_name="Imagen",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enlace",
                    models.URLField(
                        blank=True, default="", null=True, verbose_name="Enlace"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria_producto",
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Producto",
                "verbose_name_plural": "Galería de Productos",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje del descuento",
                    ),
                ),
                ("nombre", models.CharField(max_length=340)),
                (
                    "estado",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Activado"), (2, "Desactivado")], default=1
                    ),
                ),
                ("fecha_expiration", models.DateField(blank=True, null=True)),
                ("prioridad", models.IntegerField(default=0, verbose_name="prioridad")),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "by_costo",
                    models.BooleanField(default=False, verbose_name="En el costo"),
                ),
                (
                    "by_costo_caja",
                    models.BooleanField(
                        default=False, verbose_name="En el costo x Caja"
                    ),
                ),
                (
                    "by_costo_mayor",
                    models.BooleanField(
                        default=False, verbose_name="En el costo x Mayor"
                    ),
                ),
                (
                    "categorias_productos",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="descuento_categorias",
                        to="inventario.categoriaproducto",
                        verbose_name="CategoriaProducto",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="descuento_productos",
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "ordering": ("prioridad", "creado"),
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (0, "Pendiente de aprobación"),
                            (1, "Comentario aprobado"),
                            (2, "Comentario denegado"),
                        ],
                        default=0,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        default="", max_length=1000, verbose_name="Comentario"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        null=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "localizador",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        null=True,
                        verbose_name="Localizador",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentario_producto",
                        to="inventario.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ("orden",),
            },
        ),
    ]
