# Generated by Django 4.2.5 on 2023-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="teacompano-img/",
                verbose_name="Foto categoría",
            ),
        ),
        migrations.AlterField(
            model_name="galeriaproducto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="teacompano-img/",
                verbose_name="Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="teacompano-img/",
                verbose_name="Foto",
            ),
        ),
    ]
