# Generated by Django 4.2.5 on 2023-09-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_producto_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="url",
        ),
        migrations.AddField(
            model_name="producto",
            name="producturl",
            field=models.CharField(
                default="url-default",
                max_length=200,
                verbose_name="Url producto detalle",
            ),
        ),
    ]
