# Generated by Django 4.2.5 on 2023-09-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_remove_producto_url_producto_producturl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="producturl",
            new_name="url",
        ),
    ]
