# Generated by Django 4.2.5 on 2023-09-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_rename_producturl_producto_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="url",
            new_name="producturl",
        ),
    ]
